### ISSUE TITLE
Tharlon font support

### ISSUE THREAD

**Issue by danielbair** [saturngod/mmwebfonts#3]
Would you be able to add the Tharlon Regular font that my.wikipedia.com is using? https://code.google.com/p/tharlon-font/

**Comment by saturngod** [comment]
Sorry , I couldn't add. I added it when the project started. However, one of the font creator, Ngwe-Tun didn't allow to use his font on mmwebfonts. So, I removed it because he requested to remove.

If you want to use Tharlon , you can use from

http://fonts.googleapis.com/earlyaccess/tharlon.css
