### ISSUE TITLE
Questoin on use and perf

### ISSUE THREAD

**Issue by srl295** [saturngod/mmwebfonts#4]
Hello, first I like this service, am using it for the CLDR survey tool as in http://unicode.org/cldr/trac/ticket/6801#comment:13  and http://st.unicode.org/smoketest  

My question is, to save our load time and your server, rather than @including your CSS, could we just inline it in our CSS:
`@font-face { font-family:'Padauk'; src:local('Padauk'),url('http://mmwebfonts.comquas.com/fonts/padauk.ttf'); }` directly? then the only hit would be fetching the TTF, and only if it's needed.  Is the URL stable? Do you prefer including the CSS snippet URL?

**Comment by saturngod** [comment]
Padauk and Yunghkio is not working on Mac. So, if it's the mac , I need to replace with AAT support font. Now, I am using masterpiece font for mac. It's a reason why I need to use php instead of direct css.

If you want to support directly , you should use mon3 , Myanmar3 font instead of padauk.

```
@font-face {
font-family:'MON3 Anonta 1';
src:local('MON3 Anonta 1'),url('http://mmwebfonts.comquas.com/fonts/mon3.ttf');
}
```

**Comment by srl295** [comment]
Thanks. So you change the css, good to know. 
Is Mon3 standard unicode encoding and not zawgyi?
Does it make sense to reduce load and load time with direct css?

**Comment by saturngod** [comment]
mon3 is unicode font. Not zawgyi.
It can reduce the load time if you are using direct css.
